### ISSUE TITLE
Minimessage error when sending command usage.

### ISSUE THREAD

**Issue by yiyoperez** [yiyoperez/NexusBlock#28]
[19:27:23 INFO]: Sliide_ issued server command: /nb create test2
[19:27:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'nb create test2' in xhyrom.nexusblock.libs.commandmanager.bukkit.BukkitCommand(nb)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2231) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2191) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1350) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1239) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
	§8x §c/nexusblock create <nexusName> <blockMaterial>
	^^
	at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[adventure-text-minimessage-4.16.0.jar:?]
	at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[adventure-text-minimessage-4.16.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[adventure-text-minimessage-4.16.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[adventure-text-minimessage-4.16.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:79) ~[adventure-text-minimessage-4.16.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:45) ~[adventure-text-minimessage-4.16.0.jar:?]
	at xhyrom.nexusblock.utils.MessageHandler.intercept(MessageHandler.java:55) ~[NexusBlock-1.1.3.jar:?]
	at xhyrom.nexusblock.utils.MessageHandler.intercept(MessageHandler.java:34) ~[NexusBlock-1.1.3.jar:?]
	at xhyrom.nexusblock.utils.MessageHandler.sendManualMessage(MessageHandler.java:110) ~[NexusBlock-1.1.3.jar:?]
	at xhyrom.nexusblock.utils.MessageHandler.sendManualMessage(MessageHandler.java:106) ~[NexusBlock-1.1.3.jar:?]
	at xhyrom.nexusblock.services.CommandService.lambda$registerTranslations$8(CommandService.java:118) ~[NexusBlock-1.1.3.jar:?]
	at xhyrom.nexusblock.libs.commandmanager.core.message.MessageRegistry.sendMessage(MessageRegistry.java:72) ~[NexusBlock-1.1.3.jar:?]
	at xhyrom.nexusblock.libs.commandmanager.core.AbstractSubCommand.validateAndCollectArguments(AbstractSubCommand.java:273) ~[NexusBlock-1.1.3.jar:?]
	at xhyrom.nexusblock.libs.commandmanager.core.AbstractSubCommand.execute(AbstractSubCommand.java:171) ~[NexusBlock-1.1.3.jar:?]
	at xhyrom.nexusblock.libs.commandmanager.bukkit.BukkitCommand.execute(BukkitCommand.java:104) ~[NexusBlock-1.1.3.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 29 more

**Comment by yiyoperez** [comment]
Commit https://github.com/yiyoperez/NexusBlock/commit/f76ee7367cc4138093d82eb2cead3d169ad60c29 invalidates this issue.
